swagger: '2.0'
info:
  version: '1.0.0'
  title: Banks
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: localhost:8080
basePath: /
securityDefinitions:
  auth:
    type: basic
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /RestService/webapi/accounts:
    get:
      description: Get all Accounts
      tags:
      - Accounts
      operationId: get all Accounts_
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: Users response
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        401:
          description: Unauthenticated
      security:
      - auth: []
       
    post:
      description: Create a Account
      tags:
      - CreateAccount
      operationId: create new Account
      produces:
      - application/json
      parameters:
      - name: track
        in: body
        required: true
        x-is-map: false
        description: The new user details to create
        schema:
          $ref: '#/definitions/Account'
      responses:
        200:
          description: User response
          schema:
            $ref: '#/definitions/Account'
      security:
      - auth: []
 
definitions:
  Account:
    title: Account
    type: object
    properties:
      accName:
        type: string
      accNo:
        type: number
      accType:
        type: string
      amount:
        type: number
      balType:
        type: string
      currency:
        type: string
    required:
    - accName
    - accNo
    - accType
    - amount
    - balType
    - currency
